import psycopg2

conn = psycopg2.connect(dbname="duke_courses", user="uzair_chaudhry", host="localhost")
cur = conn.cursor()

BASE_URL = "https://undergraduate.bulletins.duke.edu"

programs = [
    # Bachelors
    ("African & African American Studies", "Major", "AB", "/allprograms/bachelors1/u-afri-ab"),
    ("Ancient Religion and Society, IDP", "Major", "AB", "/allprograms/bachelors1/u-irlso-ab"),
    ("Art History", "Major", "AB", "/allprograms/bachelors1/u-art-ab"),
    ("Art History and Visual Arts", "Major", "AB", "/allprograms/bachelors1/u-ahva-ab"),
    ("Asian and Middle Eastern Studies", "Major", "AB", "/allprograms/bachelors1/u-ames-ab"),
    ("Biology", "Major", "AB", "/allprograms/bachelors1/u-bio-ab"),
    ("Biology", "Major", "BS", "/allprograms/bachelors1/u-bio-bs"),
    ("Biomedical Engineering", "Major", "BSE", "/allprograms/bachelors1/u-bme-bse"),
    ("Biophysics", "Major", "AB", "/allprograms/bachelors1/u-bphy-ab"),
    ("Biophysics", "Major", "BS", "/allprograms/bachelors1/u-bphy-bs"),
    ("Brazilian and Global Portuguese Studies", "Major", "AB", "/allprograms/bachelors1/u-bpst-ab"),
    ("Chemistry", "Major", "AB", "/allprograms/bachelors1/u-chem-ab"),
    ("Chemistry", "Major", "BS", "/allprograms/bachelors1/u-chem-bs"),
    ("Civil Engineering", "Major", "BSE", "/allprograms/bachelors1/u-ce-bse"),
    ("Classical Civilization", "Major", "AB", "/allprograms/bachelors1/u-clst-ab"),
    ("Classical Languages", "Major", "AB", "/allprograms/bachelors1/u-clla-ab"),
    ("Computational Media, IDP", "Major", "AB", "/allprograms/bachelors1/u-ivmcs-ab"),
    ("Computer Science", "Major", "AB", "/allprograms/bachelors1/u-cps-ab"),
    ("Computer Science", "Major", "BS", "/allprograms/bachelors1/u-cps-bs"),
    ("Cultural Anthropology", "Major", "AB", "/allprograms/bachelors1/u-ca-ab"),
    ("Dance", "Major", "AB", "/allprograms/bachelors1/u-dance-ab"),
    ("Data Science: Math+CS, IDP", "Major", "BS", "/allprograms/bachelors1/u-idasc-bs"),
    ("Data Science: STA+CS, IDP", "Major", "BS", "/allprograms/bachelors1/u-idata-bs"),
    ("Earth and Climate Sciences", "Major", "AB", "/allprograms/bachelors2/u-ecs-ab"),
    ("Earth and Climate Sciences", "Major", "BS", "/allprograms/bachelors2/u-ecs-bs"),
    ("Economics", "Major", "AB", "/allprograms/bachelors2/u-econ-ab"),
    ("Economics", "Major", "BS", "/allprograms/bachelors2/u-econ-bs"),
    ("Electrical and Computer Engineering", "Major", "BSE", "/allprograms/bachelors2/u-ece-bse"),
    ("English", "Major", "AB", "/allprograms/bachelors2/u-engl-ab"),
    ("Environmental Engineering", "Major", "BSE", "/allprograms/bachelors2/u-enve-bse"),
    ("Environmental Sciences", "Major", "BS", "/allprograms/bachelors2/u-envs-bs"),
    ("Environmental Sciences and Policy", "Major", "AB", "/allprograms/bachelors2/u-envs-ab"),
    ("Evolutionary Anthropology", "Major", "AB", "/allprograms/bachelors2/u-evant-ab"),
    ("Evolutionary Anthropology", "Major", "BS", "/allprograms/bachelors2/u-evant-bs"),
    ("French Studies", "Major", "AB", "/allprograms/bachelors2/u-fren-ab"),
    ("Gender, Sexuality, and Feminist Studies", "Major", "AB", "/allprograms/bachelors2/u-gsf-ab"),
    ("German", "Major", "AB", "/allprograms/bachelors2/u-ger-ab"),
    ("Global Culture & Theory in the Literature Program", "Major", "AB", "/allprograms/bachelors2/u-lit-ab"),
    ("Global Health", "Major", "AB", "/allprograms/bachelors2/u-glhl-ab2"),
    ("History", "Major", "AB", "/allprograms/bachelors2/u-hist-ab"),
    ("Interdisciplinary Program in Engineering (IDEAS)", "Major", "BSE", "/allprograms/bachelors2/u-idc-bse"),
    ("International Comparative Studies", "Major", "AB", "/allprograms/bachelors2/u-ics-ab"),
    ("Italian Studies", "Major", "AB", "/allprograms/bachelors2/u-ital-ab"),
    ("Linguistics", "Major", "AB", "/allprograms/bachelors2/u-ling-ab"),
    ("Linguistics and Computer Science, IDP", "Major", "AB", "/allprograms/bachelors2/u-ilgcs-ab"),
    ("Marine Science and Conservation", "Major", "AB", "/allprograms/bachelors3/u-msc-ab"),
    ("Marine Science and Conservation", "Major", "BS", "/allprograms/bachelors3/u-msc-bs"),
    ("Mathematics", "Major", "AB", "/allprograms/bachelors3/u-math-ab"),
    ("Mathematics", "Major", "BS", "/allprograms/bachelors3/u-math-bs"),
    ("Mechanical Engineering", "Major", "BSE", "/allprograms/bachelors3/u-me-bse"),
    ("Medieval and Renaissance Studies", "Major", "AB", "/allprograms/bachelors3/u-mdvl-ab"),
    ("Music", "Major", "AB", "/allprograms/bachelors3/u-mus-ab"),
    ("Neuroscience", "Major", "AB", "/allprograms/bachelors3/u-neur-ab"),
    ("Neuroscience", "Major", "BS", "/allprograms/bachelors3/u-neur-bs"),
    ("Philosophy", "Major", "AB", "/allprograms/bachelors3/u-phil-ab"),
    ("Physics", "Major", "AB", "/allprograms/bachelors3/u-phys-ab"),
    ("Physics", "Major", "BS", "/allprograms/bachelors3/u-phys-bs"),
    ("Political Science", "Major", "AB", "/allprograms/bachelors3/u-poli-ab"),
    ("Psychology", "Major", "AB", "/allprograms/bachelors3/u-psy-ab"),
    ("Psychology", "Major", "BS", "/allprograms/bachelors3/u-psy-bs"),
    ("Public Policy", "Major", "AB", "/allprograms/bachelors3/u-pps-ab"),
    ("Religion", "Major", "AB", "/allprograms/bachelors3/u-rel-ab"),
    ("Romance Studies", "Major", "AB", "/allprograms/bachelors3/u-rom-ab"),
    ("Russian", "Major", "AB", "/allprograms/bachelors3/u-rus-ab"),
    ("Slavic and Eurasian Studies", "Major", "AB", "/allprograms/bachelors3/u-ses-ab"),
    ("Sociology", "Major", "AB", "/allprograms/bachelors3/u-soc-ab"),
    ("Spanish", "Major", "AB", "/allprograms/bachelors3/u-span-ab"),
    ("Statistical Science", "Major", "AB", "/allprograms/bachelors3/u-sta-ab"),
    ("Statistical Science", "Major", "BS", "/allprograms/bachelors3/u-sta-bs"),
    ("Theater Studies", "Major", "AB", "/allprograms/bachelors3/u-thea-ab"),
    ("Visual and Media Studies", "Major", "AB", "/allprograms/bachelors3/u-vis-ab"),
    ("Visual Arts", "Major", "AB", "/allprograms/bachelors3/u-artv-ab"),
    # Minors
    ("African & African American Studies", "Minor", "", "/allprograms/minors1/u-afri-min"),
    ("Art History", "Minor", "", "/allprograms/minors1/u-art-min"),
    ("Asian and Middle Eastern Studies", "Minor", "", "/allprograms/minors1/u-ames-min"),
    ("Biology", "Minor", "", "/allprograms/minors1/u-bio-min"),
    ("Brazilian and Global Portuguese Studies", "Minor", "", "/allprograms/minors1/u-bpst-min"),
    ("Chemistry", "Minor", "", "/allprograms/minors1/u-chem-min"),
    ("Cinematic Arts", "Minor", "", "/allprograms/minors1/u-cine-min"),
    ("Classical Archaeology", "Minor", "", "/allprograms/minors1/u-clar-min"),
    ("Classical Civilizations", "Minor", "", "/allprograms/minors1/u-clcz-min"),
    ("Computational Biology and Bioinformatics", "Minor", "", "/allprograms/minors1/u-cpsb-min"),
    ("Computational Media", "Minor", "", "/allprograms/minors1/u-cmac-min"),
    ("Computer Science", "Minor", "", "/allprograms/minors1/u-cps-min"),
    ("Computer Science Artificial Intelligence", "Minor", "", "/allprograms/minors1/u-cpsai-m"),
    ("Creative Writing", "Minor", "", "/allprograms/minors1/u-wrtg-min"),
    ("Cultural Anthropology", "Minor", "", "/allprograms/minors1/u-ca-min"),
    ("Dance", "Minor", "", "/allprograms/minors1/u-dan-min"),
    ("Economics", "Minor", "", "/allprograms/minors2/u-econ-min"),
    ("Education", "Minor", "", "/allprograms/minors2/u-educ-min"),
    ("Electrical and Computer Engineering", "Minor", "", "/allprograms/minors2/u-ece-min"),
    ("Energy Engineering", "Minor", "", "/allprograms/minors2/u-ene-min"),
    ("English", "Minor", "", "/allprograms/minors2/u-engl-min"),
    ("Environmental Sciences and Policy", "Minor", "", "/allprograms/minors2/u-envs-min"),
    ("Financial Economics", "Minor", "", "/allprograms/minors2/u-ecofin-m"),
    ("French Studies", "Minor", "", "/allprograms/minors2/u-fren-min"),
    ("German", "Minor", "", "/allprograms/minors2/u-ger-min"),
    ("Global Culture & Theory in the Literature Program", "Minor", "", "/allprograms/minors2/u-lit-min"),
    ("Greek", "Minor", "", "/allprograms/minors2/u-grk-min"),
    ("History", "Minor", "", "/allprograms/minors2/u-hist-min"),
    ("Inequality Studies", "Minor", "", "/allprograms/minors2/u-hist-ine"),
    ("Italian Studies", "Minor", "", "/allprograms/minors2/u-ital-min"),
    ("Journalism and Media", "Minor", "", "/allprograms/minors2/u-jam-min"),
    ("Latin", "Minor", "", "/allprograms/minors2/u-lat-min"),
    ("Linguistics", "Minor", "", "/allprograms/minors2/u-ling-min"),
    ("Machine Learning and Artificial Intelligence", "Minor", "", "/allprograms/minors3/u-ece-mlai"),
    ("Marine Science and Conservation", "Minor", "", "/allprograms/minors3/u-msc-min"),
    ("Mathematics", "Minor", "", "/allprograms/minors3/u-math-min"),
    ("Medical Sociology", "Minor", "", "/allprograms/minors3/u-medsoc-m"),
    ("Medieval and Renaissance Studies", "Minor", "", "/allprograms/minors3/u-mdvl-min"),
    ("Music", "Minor", "", "/allprograms/minors3/u-mus-min"),
    ("Music Listening-Focused", "Minor", "", "/allprograms/minors3/u-musl-min"),
    ("Musical Theater", "Minor", "", "/allprograms/minors3/u-musthe-m"),
    ("Philosophy", "Minor", "", "/allprograms/minors3/u-phil-min"),
    ("Photography", "Minor", "", "/allprograms/minors3/u-phtg-min"),
    ("Physics", "Minor", "", "/allprograms/minors3/u-phys-min"),
    ("Political Science", "Minor", "", "/allprograms/minors3/u-poli-min"),
    ("Psychology", "Minor", "", "/allprograms/minors3/u-psy-min"),
    ("Religion", "Minor", "", "/allprograms/minors3/u-rel-min"),
    ("Russian", "Minor", "", "/allprograms/minors3/u-rus-min"),
    ("Russian and East European Literature in Translation", "Minor", "", "/allprograms/minors3/u-rlt-min"),
    ("Sociology", "Minor", "", "/allprograms/minors3/u-soc-min"),
    ("Software Engineering", "Minor", "", "/allprograms/minors3/u-swe-min"),
    ("Spanish", "Minor", "", "/allprograms/minors3/u-span-min"),
    ("Statistical Science", "Minor", "", "/allprograms/minors3/u-sta-min"),
    ("Theater Studies", "Minor", "", "/allprograms/minors3/u-thea-min"),
    ("Visual and Media Studies", "Minor", "", "/allprograms/minors3/u-vis-min"),
    ("Visual Arts", "Minor", "", "/allprograms/minors3/u-artv-min"),
    ("Writing and Rhetoric", "Minor", "", "/allprograms/minors3/u-wrrh-min"),
    # Certificates
    ("Aerospace Engineering", "Certificate", "", "/allprograms/certificate/u-aeregr-c"),
    ("Architectural Engineering", "Certificate", "", "/allprograms/certificate/u-arc-c"),
    ("Carceral Studies", "Certificate", "", "/allprograms/certificate/u-carc-c"),
    ("Digital Intelligence", "Certificate", "", "/allprograms/certificate/u-dq-c"),
    ("Energy and the Environment", "Certificate", "", "/allprograms/certificate/u-enrenv-c"),
    ("Global Development Engineering", "Certificate", "", "/allprograms/certificate/u-gbldev-c"),
    ("Health Policy", "Certificate", "", "/allprograms/certificate/u-hlthpl-c"),
    ("Human Rights", "Certificate", "", "/allprograms/certificate/u-hmnrgt-c"),
    ("Markets and Management", "Certificate", "", "/allprograms/certificate/u-mmst-c"),
    ("Philosophy, Politics and Economics", "Certificate", "", "/allprograms/certificate/u-ppe-c"),
    ("Robotics and Automation", "Certificate", "", "/allprograms/certificate/u-robot-c"),
    ("Science and the Public", "Certificate", "", "/allprograms/certificate/u-gsp-c"),
]

for pname, ptype, degree_type, url in programs:
    bulletin_url = BASE_URL + url
    cur.execute("""
        INSERT INTO Program (pname, ptype, degree_type, school, valid_from_yr, valid_to_yr, bulletin_url)
        VALUES (%s, %s, %s, %s, %s, %s, %s)
    """, (pname, ptype, degree_type, "Duke University", 2024, 2026, bulletin_url))

conn.commit()
print(f"Seeded {len(programs)} programs")
cur.close()
conn.close()